#!/usr/bin/env bash
# unpre.sh — Undo preparation: remove repo/keyring/cache/state and revert docker group/user changes.
# Reads state file generated by pre.sh.
set -euo pipefail

STATE_FILE="${STATE_FILE:-/var/lib/docker-install/state.env}"

if [[ ! -f "$STATE_FILE" ]]; then
  echo "[FATAL] STATE_FILE not found: $STATE_FILE"
  exit 1
fi

# shellcheck disable=SC1090
. "$STATE_FILE"

LOG_FILE="${LOG_DIR}/unpre.sh.log"
exec > >(tee -a "$LOG_FILE") 2>&1
echo "[START] unpre.sh $(date -u +'%Y-%m-%dT%H:%M:%SZ')"

require() {
  local v="$1"
  if [[ -z "${!v:-}" ]]; then
    echo "[FATAL] Missing state var: $v"; exit 1
  fi
}

require LOG_DIR
require CACHE_DIR
require STATE_DIR
require KEYRING_DIR
require REPO_DIR
require DOCKER_LIST
require DOCKER_KEYRING
require TARGET_USER
require DOCKER_GROUP_CREATED
require USER_ADDED_TO_DOCKER

# Revert user from docker group if we added
echo "[STEP] Revert user/group changes..."
if [[ "${USER_ADDED_TO_DOCKER}" == "1" ]]; then
  if id -nG "${TARGET_USER}" 2>/dev/null | tr ' ' '\n' | grep -qx docker; then
    if gpasswd -d "${TARGET_USER}" docker; then
      echo "  removed '${TARGET_USER}' from 'docker'"
    else
      echo "  [WARN] failed to remove '${TARGET_USER}' from 'docker'"
    fi
  fi
fi

# Remove docker group if we created it (and empty)
if [[ "${DOCKER_GROUP_CREATED}" == "1" ]]; then
  if getent group docker >/dev/null 2>&1; then
    if [[ -z "$(getent group docker | awk -F: '{print $4}')" ]]; then
      groupdel docker && echo "  deleted group 'docker'" || echo "  [WARN] failed to delete 'docker' group"
    else
      echo "  [INFO] 'docker' group not empty; skipping deletion"
    fi
  fi
fi

# Remove repo + keyring
echo "[STEP] Remove Docker APT repo and key..."
rm -f "$DOCKER_LIST" "$DOCKER_KEYRING"

# apt update
apt-get update -y || true

# Remove cache dir
echo "[STEP] Remove cache directory..."
rm -rf "$CACHE_DIR"

# Remove manifest + state
echo "[STEP] Remove manifest & state..."
rm -f "${MANIFEST_FILE:-}"
rm -rf "$STATE_DIR"

echo "[DONE] unpre.sh completed at $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
