#!/bin/bash

input="Call us at (123) 456-7890 or (555) 555-5555."
regex="\(\d{3}\) \d{3}-\d{4}"

output=$(echo "$input" | grep -o -E "$regex")

echo "INPUT = $input"
echo "RegEx = $regex"
echo "Output = $output"